<?php  
$region = array(

    "estado"=> 'Ciudad',
    "municipio"=>'',
    'direccion'=> 'Localidad o barrio',
    'precio_sugerido_pequeno' => '20.000',
    'precio_sugerido_mediano' => '25.000',
    'precio_sugerido_grande'  => '30.000',
    'precio_sugerido_gigante' => '40.000',
    'cuidador_descripcion' => '¡Hola! Soy ________, tengo ___ años y me encantan los animales. Estaré 100% al cuidado de tu perrito, lo consentiré y recibirás fotos diarias de su estancia conmigo. Mis huéspedes peludos duermen dentro de casa SIN JAULAS NI ENCERRADOS. Cuento con _______ para que jueguen, además cerca de casa hay varios parques donde los saco a pasear diariamente. En su estadía tu mascota contará con cobertura de gastos veterinarios, que en caso de emergencia se encuentra dentro de mi barrio, de confianza y muy cerca de mi casa. Cualquier duda que tengas no dudes en contactarme.',
    "pais" => "Colombia",
    "pais_cod_iso"   => "CO",
    'moneda_cod' => 'COP',
    "titulo"     => "Kmimos Colombia",
    "email" => "contactoco@kmimos.la",
    "telefono"   => " Bogota:+57 (1) 593 8719",
    "telefono_corrido" => "+5715938719",
    "whatsapp" => "+57 318 350 2391", 
    "twitter" => "kmimosco",
    "facebook" => "Kmimosco",
    "instagram" => "kmimosco",
    "mon_izq" => "",
    "mon_der" => "COP",
    "km-vacaciones" => false,
    "km-medios" => false,
    "km-patitas" => false,
    "km-5000" => 0,
    "conocio" => array(
        'Facebook' => 'Facebook',
        'Adwords' => 'Buscador de Google',
        'Twitter' => 'Twitter',
        'Amigo/Familiar' => 'Recomendación de amigo o familiar',
        'Youtube' => 'Youtube',
        'Otros' => 'Otros'
    ),
    "identidad" => "Cédula de Ciudadanía /DNI",
    "identidad-length" => 7,
    "meta_key_pdf_tienda" => "_payu_pdf",
    "meta_key_tienda_vence" => "_payu_tienda_vence",
    "web" => "http://kmimos.co",
    "comision" => "",

);