<?php
$HTML_TERMINOS = '<div style="text-align: justify">
<strong><u>I. Términos y Condiciones Kmimos.</u></strong>
<strong>1. Utilización de este Sitio. </strong>
<p>1.1. Este es el sitio en la red de <strong>Kmimos</strong> (el "Sitio"), mismo que incluye todos los recursos disponibles contenidos en el nombre de dominio "<strong>kmimos</strong>.mx", “<strong>kmimos</strong>.la”, "<strong>kmimos</strong>.com.mx", "cani.mx". Por el sólo hecho de ingresar a, o utilizar este Sitio, usted (el "Usuario"), (i) manifiesta haber leído, entendido y aceptado incondicionalmente los términos y condiciones de uso (los "Términos") del Sitio que a continuación se detallan; y (ii) se compromete a hacer uso del mismo estrictamente bajo los Términos, aceptando que dicha utilización le atribuye la calidad de usuario del Sitio e implica la adhesión plena y sin reservas a todos y cada uno de los Términos. En caso de que usted no esté de acuerdo con los Términos, por favor absténgase de utilizar este Sitio. </p>
<strong>2. Condiciones de Utilización. </strong>
<p>2.1. El Usuario se compromete a utilizar el Sitio de acuerdo con estos Términos y las normas jurídicas vigentes en los Estados Unidos Mexicanos, así como se obliga a no usar el Sitio con fines ilícitos, contrarios a estos Términos, lesivos a los intereses de terceros, o de tal manera que puedan dañar, sobrecargar, deteriorar o inutilizar el Sitio. </p>
<p>2.2. El Usuario manifiesta saber y entender que el Sitio está destinado a Usuarios que no son consumidores para los efectos de la Ley Federal de Protección al Consumidor. Asimismo, manifiesta que el uso que haga del Sitio, así como cualquier negociación o acto jurídico relacionado con el Sitio, lo hace con la intención de integrar los bienes y/o servicios en su caso involucrados a una o varias cadenas productivas, por lo que el Usuario en ningún momento será un consumidor, ni <strong>Kmimos</strong> un proveedor, para los efectos de la mencionada Ley. </p>
<p>2.3. El Usuario se obliga a abstenerse de obtener o intentar obtener, publicar o distribuir por cualquier medio todo tipo de informaciones, sellos, mensajes, imágenes, software o cualquier clase de material contenido en el Sitio, sirviéndose de medios distintos a los señalados en el Sitio. </p>
<p>2.4. El Usuario deberá cumplir estrictamente con cualquier instrucción o indicación contenida en el Sitio o proporcionada por personal autorizado de <strong>Kmimos</strong> relativa a la utilización del Sitio. </p>
<p>2.5. El Usuario es responsable de la veracidad, exactitud, vigencia y autenticidad de la Información proporcionada a <strong>Kmimos</strong> y, asimismo se compromete a mantenerla actualizada. Al agregar el Usuario contenido al Sitio como comentarios, propiedades, aplicaciones, preguntas, respuestas e incluso contenido protegido por derechos de propiedad intelectual como fotografías y vídeos, lo hace otorgando a <strong>Kmimos</strong> una licencia indefinida, no exclusiva, transferible, con posibilidad de ser sub-otorgada, sin royalties, aplicable globalmente, para utilizar cualquier contenido que el usuario publique en el Portal.</p>
<p>Valoramos todas las aportaciones de nuestros usuarios al Sitio, pero debemos ser claros que <strong>Kmimos</strong> podría utilizarlas en cualquier momento sin obligación de compensar al usuario por ello (del mismo modo que el usuario no tiene obligación de aportar).</p>
<p>2.6 La Información que sea incluida en catálogos, directorios o cualquier otro instrumento análogo será únicamente aquella que permita establecer una adecuada relación entre compradores y proveedores o viceversa. </p>
<p>2.7 La Información proporcionada por los Usuarios podrá ser utilizada por <strong>Kmimos</strong> para el logro de los fines del Sitio, incluso después de que haya concluido el uso por el Usuario, o la prestación de servicios por parte de <strong>Kmimos</strong>. </p>
<p>2.8. El Usuario se compromete a hacer un uso diligente del registro ("Registro") que le sea otorgado para hacer uso de los servicios ofrecidos en el Sitio. El Registro será otorgado discrecionalmente por <strong>Kmimos</strong> y se compondrá de dos partes: un nombre de identificación para efectos del Sitio (Nombre), y una contraseña confidencial (Contraseña) para poder ingresar a las páginas restringidas del Sitio, así como publicar información en el mismo. El Nombre y Contraseña serán elegidos por el Usuario; en caso de que el Nombre no esté disponible, el Usuario deberá elegir otro, hasta elegir uno disponible. Tanto el Nombre como la Contraseña respectiva son INTRANSFERIBLES, por lo que el Usuario será el único responsable del uso que se haga tanto de su nombre como de su Contraseña, y se compromete a responder incondicionalmente de cualquier obligación, responsabilidad o compromiso que resulten de, o se relacionen con, el uso de su Nombre y/o Contraseña. El Usuario será responsable de mantener en confidencialidad y a su vez será responsable absoluto por todas las actividades que ocurran bajo su nombre o Contraseña. En virtud de lo anterior el usuario deberá: (a) notificar inmediatamente a <strong>Kmimos</strong> de cualquier uso no autorizado de su nombre o Contraseña o de cualquier otra falla de seguridad, y (b) asegurarse de que su cuenta sea cerrada al final de cada sesión. <strong>Kmimos</strong> no será responsable por ninguna pérdida o daño que resulte como consecuencia de su incumplimiento a estas disposiciones. </p>
<p>2.9. El Registro puede ser suspendido o cancelado por el Usuario o por <strong>Kmimos</strong> en cualquier tiempo, previa notificación a la otra parte y en el entendido de que hayan concluido todos los compromisos generados por la prestación del servicio. Sin perjuicio de lo anterior, <strong>Kmimos</strong> podrá cancelar unilateralmente el registro del Usuario. </p>
<p>2.10. <strong>Kmimos</strong> se reserva el derecho de prestación de los servicios ofrecidos en el Sitio. <strong>Kmimos</strong> no tiene control sobre la conducta de los usuarios, perros, dueños del perro, o cualesquiera otros usuarios del sitio o servicios proporcionados, y <strong>Kmimos</strong> renuncia a toda responsabilidad al respecto</p>
<p>2.11. Cualquier persona que pretenda incluir en su sitio o portal un hipervínculo al Sitio, deberá cumplir con los siguientes requisitos:</p>
<p>El hipervínculo sólo permitirá el acceso al Sitio, pero no podrá reproducir en forma alguna sus contenidos; </p>
<p>No se harán declaraciones o manifestaciones falsas, inexactas o incorrectas sobre el Sitio, ni se dará a entender que <strong>Kmimos</strong> ha asumido de cualquier forma los contenidos o servicios que se hayan ofrecido en el sitio o portal en el que se encuentre el hipervínculo;</p>
<p>El sitio o portal en el que se establezca el hipervínculo no contendrá ninguna marca, nombre comercial, denominación, logotipo, eslogan o cualquier otro signo distintivo respecto de los cuales <strong>Kmimos</strong> sea titular o tenga una licencia exclusiva de uso, con excepción del nombre de dominio que forme parte del hipervínculo o bien bajo autorización escrita de <strong>Kmimos</strong>. </p>
<p>El sitio o portal en el que se establezca el hipervínculo no deberá tener contenidos ilícitos o que violen derechos de terceros;</p>
<p>El hecho de que en un sitio o portal haya un hipervínculo al Sitio, no implica la existencia de relaciones de cualquier tipo entre <strong>Kmimos</strong> y el titular del sitio o portal que contenga el hipervínculo. </p>
<p>2.12. El Sitio, a su vez, puede contener hipervínculos a otros sitios o portales. <strong>Kmimos</strong> no hace declaración alguna respecto de cualquier sitio o portal al que se pueda acceder desde este Sitio. <strong>Kmimos</strong> no tiene ningún tipo de relación con dichos sitios o portales y, por lo tanto, no se responsabiliza de los productos y/o servicios adquiridos en esos sitios o portales, ni tampoco se responsabiliza de su contenido. </p>
<p>2.13. El Usuario será responsable de cualquier daño y/o perjuicio que <strong>Kmimos</strong> sufra como consecuencia del incumplimiento de los términos por parte del Usuario.</p>
<p>2.14. El Usuario será responsable de los servicios que ofrezca a través del sitio de <strong>Kmimos</strong> , así como de los bienes, inmuebles, u objetos propios o de algún tercer usuario que le haya contratado algún servicio. <strong>Kmimos</strong> no es responsable ni está sujeto a pagar ninguna indemnización a los usuarios por los daños o perjuicios que se puedan generar a estos bienes, inmuebles, u objetos.</p>
<strong>3. Garantías. </strong>
<p>3.1. Este Sitio y todos los datos, información, documentos, programas, materiales de mercadeo y declaraciones técnicas contenidas en el mismo, se proporcionan sin garantías de ningún tipo, tácitas o expresas, incluyendo sin limitación alguna, garantías de comerciabilidad o idoneidad para cualquier propósito. </p>
<p>3.2. <strong>Kmimos</strong> no se hace responsable del desarrollo y conclusión de las operaciones que se realicen en el Sitio ni de la documentación comprobatoria de éstas. De igual forma, <strong>Kmimos</strong> no responde de la calidad, cantidad o cualquiera otra característica de los productos y/o servicios ofertados en el Sitio ya que éstas son responsabilidad de los Usuarios. </p>
<p>3.3. <strong>Kmimos</strong> no ha intervenido ni se hace responsable de ningún acuerdo o contrato celebrado entre los usuarios antes o después de hacer uso de los servicios ofrecidos en el Sitio.</p>
<p>3.4. <strong>Kmimos</strong> se encarga de poner en contacto a los distintos Usuarios del Sitio, pero de ninguna manera se hace responsable de los daños o perjuicios que se ocasionen por las operaciones realizadas en él o entre ellos, o por los daños o perjuicios que se ocasionen a los bienes, inmuebles, u objetos de alguno de los usuarios. </p>
<p>3.5. <strong>Kmimos</strong> no garantiza la ausencia de virus en el Sitio, así como no se garantiza la ausencia de otros elementos que puedan producir alteraciones en el Software o Hardware del sistema informático del Usuario, o en los documentos electrónicos y ficheros almacenados en su sistema informático. </p>
<strong>EL USUARIO EXPRESAMENTE COMPRENDE Y CONVIENE EN QUE:</strong>
<p>El uso del servicio es bajo su propio riesgo. El servicio es provisto y según se encuentre "disponible". <strong>Kmimos</strong> no garantiza que (i) el servicio se ajustará a sus requisitos, (ii) el servicio será ininterrumpido, puntual, seguro, o libre de error, (iii) los resultados que puedan ser obtenidos del uso del servicio sean veraces o confiables, (iv) la calidad de cualquier producto, servicio, información, u otro material comprado u obtenido por usted por medio del servicio se ajustará a sus expectativas y (v) cualquier error en el software será corregido. Cualquier material descargado o de cualquier otra forma obtenido por medio del uso del servicio es hecho bajo su propia discreción y riesgo y usted será absolutamente responsable por cualquier daño al sistema de su computadora o pérdida de datos que resulte de la descarga de cualquiera de estos materiales. Ningún consejo o información, ya sea oral o escrito, obtenido de <strong>Kmimos</strong> por usted, o por medio del servicio constituirá garantía alguna, a no ser que se encuentre expresamente establecido.</p>
<strong>4. Excluyentes de Responsabilidad. </strong>
<p>4.1. Este Sitio incluye información, documentos y gráficos que pueden contener inexactitudes técnicas o errores tipográficos. Parte del contenido del sitio ha sido aportado por usuarios, por lo que pueden contener inexactitudes técnicas o ser falsos. <strong>Kmimos</strong> no se responsabiliza por la exactitud de la información y se reserva el derecho de mejorar o cambiar en cualquier momento cualquier contenido del Sitio. Si usted detecta alguna inexactitud o error, háganoslo saber de inmediato a contactomex@<strong>kmimos</strong>.la </p>
<p>Mal Uso de Información: <strong>Kmimos</strong> ha tomado medidas para detectar usos no adecuados de la información del sitio, sea para utilizar, reproducir, subir o modificar información de forma maliciosa o no autorizada. En estos casos se procederá legalmente contra quien sea responsable de acuerdo a las leyes aplicables en México e internacionales.</p>
<p>4.2. En ningún caso <strong>Kmimos</strong> será responsable frente al Usuario o frente a algún tercero por cualquier daño y/o perjuicio directo, indirecto, incidental, o de cualquier tipo que haya sufrido el Usuario o el tercero por el acceso o el uso del Sitio o la contratación de un servicio a un tercer usuario del Sitio o de cualquier otro portal o sitio al que se haya tenido acceso por medio del Sitio </p>
<p>4.3. <strong>Kmimos</strong> ofrece asesoría técnica en línea para los Usuarios registrados en el Sitio. El tiempo estimado de respuesta indicado en el Sitio para este servicio, no es bajo ninguna circunstancia obligatorio para <strong>Kmimos</strong>, por lo que <strong>Kmimos</strong> se reserva el derecho de responder al Usuario en menor o mayor tiempo que el indicado, o bien de no hacerlo del todo sin necesidad de explicaciones o aclaraciones y sin responsabilidad alguna para <strong>Kmimos</strong> frente al Usuario o frente a algún tercero. Las recomendaciones que haga <strong>Kmimos</strong> serán hechas de buena fe, pero <strong>Kmimos</strong> no garantiza que éstas sean correctas, viables o adecuadas para resolver el problema planteado por el Usuario, por lo que en ningún caso será <strong>Kmimos</strong> responsable frente al Usuario o frente a algún tercero por cualquier daño y/o perjuicio directo, indirecto, incidental, o de cualquier tipo que haya sufrido el Usuario o un tercero por seguir las recomendaciones de <strong>Kmimos</strong>, independientemente de cuáles hayan sido éstas y de cómo hayan sido comunicadas al Usuario. </p>
<p>4.4 El usuario se compromete a indemnizar y sacar en paz y a salvo, libre de daños a <strong>Kmimos</strong> y a sus agentes, subsidiarias, afiliados, oficiales, asociados u otros socios y empleados de cualquier reclamo o demanda, incluyendo honorarios razonables de los abogados, hecha por una tercera parte debido a la información, o información surgida del contenido que el usuario incluya, presente, anuncie o transmita por medio del servicio, su uso del servicio, su violación a estas políticas, o la violación a los derechos de un tercero . </p>
<p>4.5 La correspondencia o tratos del usuario con anunciantes, o su participación en promociones de anunciantes encontrados en el portal o por medio del portal, incluyendo el pago y la entrega de los bienes o servicios relacionados, y cualesquiera otros términos y condiciones, garantías o representaciones asociadas con dichos tratos, serán únicamente entre usted y dicho anunciante. Usted reconoce y conviene en que <strong>Kmimos</strong> no será responsable o tendrá obligación legal por pérdida o daño de ningún tipo que resulte de dichos tratos, o que sea el resultado de la presencia de dichos anunciantes en el portal. </p>
<strong>5. Derechos de Autor. </strong>
<p>5.1. Todas las obras artísticas y literarias contenidas en el Sitio se encuentran protegidas por la Ley Federal del Derecho de Autor, son de la titularidad de <strong>Kmimos</strong>, han sido licenciadas a <strong>Kmimos</strong>, o bien se utilizan conforme al artículo 23 de la Ley Federal del Derecho de Autor a solicitud de los clientes de <strong>Kmimos</strong>. </p>
<p>5.2. Debido a lo anterior, se prohíbe la reproducción total o parcial de los datos e información contenidos en el Sitio, por cualquier medio y por cualquier forma; también se prohíbe la modificación, mutilación, deformación o transformación del contenido del Sitio, así como la copia o reproducción de las bases de datos. </p>
<p>5.3. El acceso al Sitio y el uso de los servicios proporcionados en el mismo no confieren ningún derecho sobre la titularidad de las obras contenidas en el Sitio, ni la adquisición de ninguna licencia sobre los derechos de autor. </p>
<strong>6. Derechos de Propiedad Industrial. </strong>
<p>6.1. <strong>Kmimos</strong> es una marca registrada, por lo que no podrá utilizarse sin la previa autorización por escrito de <strong>Kmimos</strong>, S.A.P.I. de C.V. </p>
<p>6.2. Todos los elementos de Propiedad Industrial que aparecen en el Sitio son titularidad de <strong>Kmimos</strong> o de sus clientes, o bien han sido licenciados por sus titulares a <strong>Kmimos</strong> o a sus clientes, por lo que tampoco podrán ser usados sin la autorización respectiva. Si usted considera que algún elemento infringe sus derechos o los de su representado háganoslo saber de inmediato a través de la sección de Protección de Derechos (Copyright).</p>
<p>6.3. El acceso al Sitio y el uso de los servicios proporcionados en el mismo no confieren ningún derecho sobre la titularidad de las marcas, nombres comerciales, eslóganes, logotipos y demás signos distintivos, así como otros derechos de propiedad industrial relativos al contenido del Sitio, ni la adquisición de ninguna licencia sobre tales derechos. </p>
<p>6.4. Para lo relativo a este inciso y sus subincisos, se entiende por "Expresión" a una palabra o conjunto de palabras que escribe un Usuario en la funcionalidad de "búsqueda por producto" que ofrece el Sitio. A través de dicha Expresión, un Usuario puede referirse a un producto, a un servicio, a una línea de productos o servicios y/o a una marca registrada. </p>
<p>6.4.1. Al buscar una Expresión en el Sitio, los resultados de la búsqueda pueden mostrar lo siguiente: a) compañías ("Empresas") que dicen poder ofrecer productos/servicios a los que se refiere la Expresión y/o b) compañías ("Otras Empresas") que sin poder ofrecer productos/servicios a los que se refiere la Expresión, creen (más de ninguna manera garantizan) poder ofrecer productos/servicios relacionados con alguna de las industrias a las que se destina el producto/servicio al que se refiere la Expresión. </p>
<p>6.4.2. Lo anterior significa que las Otras Empresas podrían potencialmente ofrecer a dicha industria, productos o servicios de cualquier tipo, por ejemplo: servicio técnico, servicios logísticos, servicios financieros, consultoría ambiental o de otra índole, maquinaria y/o equipo, estudios de mercado, productos/servicios sustitutos, alternativos, complementarios o reciclaje de los productos/servicios amparados por la Expresión. </p>
<p>6.4.3. Dado que sería sumamente difícil verificar los productos, servicios y/o marcas registradas que una compañía puede ofrecer, y en vista de que <strong>Kmimos</strong> no tiene interés ni obtiene beneficio alguno al publicar información poco precisa, inexacta, desactualizada o errónea, <strong>Kmimos</strong> no garantiza que una compañía pueda efectivamente ofrecer los productos/servicios, familias de productos/servicios y/o marcas registradas mostrados en el Sitio o almacenados en las bases de datos de <strong>Kmimos</strong>. <strong>Kmimos</strong> obtiene esa información de las compañías y la proporciona de buena fe a sus Usuarios, sin embargo tampoco ofrece garantía de que dicha información sea exacta, actual o correcta y por lo tanto no asume ni acepta responsabilidad alguna por errores u omisiones en la misma o por daños de cualquier índole que se deriven de su uso, cualquiera que éste sea.</p>
<p>En caso de que se observe información publicada que infrinja derechos de autor, patentes, marcas registradas o derechos de propiedad intelectual o industrial, el propietario de estos derechos podrá dar aviso siguiendo el procedimiento definido en la sección de Protección de Derechos (Copyright).</p>
<p>6.4.4. Ni <strong>Kmimos</strong> ni las Otras Empresas sugieren, dan por hecho ni aseguran que: </p>
<p>6.4.4.1. Los productos y/o servicios que las Otras Empresas pueden ofrecer, sean iguales, similares, contratipos, equivalentes ni intercambiables con los productos/servicios amparados por la Expresión buscada, independientemente de que dicha Expresión incluya o coincida total o parcialmente con un nombre de producto/servicio, una familia de productos/servicios o una marca registrada. </p>
<p>6.4.4.2. Los productos amparados bajo una marca registrada sean iguales, similares ni equivalentes a los que ampara otra marca registrada, ni que dos marcas registradas ni los productos que éstas amparan, sean intercambiables entre sí. </p>
<strong>7. Información Confidencial.</strong>
<p>7.1. La información que los Usuarios nos proporcionan se utiliza con el único fin de prestar un mejor servicio, por lo que no se transmitirán a terceros sin la previa autorización del Usuario. <strong>Kmimos</strong> garantiza la confidencialidad de los datos personales del Usuario. </p>
<p>7.2. <strong>Kmimos</strong> garantiza que se han adoptado las medidas oportunas de seguridad en sus instalaciones, sistemas y ficheros. </p>
<p>7.3. <strong>Kmimos</strong> no será responsable cuando la información confidencial se proporcione a autoridades públicas competentes, cuando así lo dispongan las normas jurídicas aplicables o por solicitud explícita de las autoridades. </p>
<p>7.4. El Usuario garantiza y responde por la veracidad, exactitud, vigencia y autenticidad de cualquier información proporcionada a <strong>Kmimos</strong> y asimismo se compromete a mantenerla actualizada. </p>
<p>7.5. Con el fin de proporcionar un mejor servicio, <strong>Kmimos</strong> puede llegar a usar cookies para una mejor identificación del Usuario, mismo que autoriza la realización de esta práctica. </p>
<strong>8. Autonomía de disposiciones. </strong>
<p>8.1. La nulidad, invalidez, ilegalidad o cualquier vicio en cualquiera de las disposiciones de los presentes Términos, sólo afectará a dicha disposición, y por lo tanto no afectará a las demás disposiciones aquí pactadas, las cuales conservarán por entero su fuerza obligatoria. </p>
<strong>9. Encabezados y Definiciones.</strong>
<p>9.1. Los encabezados o títulos de estos Términos se incluyen únicamente para facilitar la referencia, y no limitan o afectan de otra manera los términos y las condiciones de estos Términos. </p>
<strong>10. Derecho Aplicable y Jurisdicción. </strong>
<p>10.1. <strong>Kmimos</strong> presta sus servicios en el territorio de la República Mexicana, por lo que <strong>Kmimos</strong> no declara que el contenido del Sitio sea apropiado o disponible para su uso en otros lugares, ni será responsable por el acceso que al Sitio hagan personas que se encuentren en lugares donde el contenido del Sitio pudiera ser ilícito. Aquellos que accedan al Sitio lo harán por su propia iniciativa y serán responsables para los efectos de las leyes locales que les sean aplicables. Este sitio, así como cualquier asunto o cuestión relacionada con el mismo o su uso se rigen por las leyes mercantiles de los Estados Unidos Mexicanos. </p>
<p>10.2. En caso de cualquier disputa, controversia, reclamación o diferencia que surja de, o se relacione con la utilización de este Sitio, incluidas las políticas de privacidad de <strong>Kmimos</strong>, será resuelta y decidida definitivamente mediante arbitraje, regido por el Reglamento de Arbitraje Comercial de la Asociación Mexicana de Mediación y Arbitraje Comercial, A.C. (la "AMMAC"). El arbitraje será resuelto por un árbitro, el cual será nombrado por la AMMAC. El idioma a utilizarse en el arbitraje será español. El lugar del arbitraje será la Ciudad de México, sin perjuicio de que se puedan practicar diligencias y llevar a cabo audiencias en cualquier parte. En caso de que por cualquier motivo la AMMAC estuviera en imposibilidad de administrar el arbitraje, las partes acuerdan que la Asociación Americana de Arbitraje (American Arbitration Association) de Nueva York administrará dicho arbitraje, y las reglas de arbitraje comercial internacional de la misma serán aplicables. </p>
<strong>11. Compensación en caso de accidente. (Cobertura de servicios veterinarios)</strong>
<p>No obstante <strong>Kmimos</strong> funge como una plataforma y puente de comunicación entre el cuidador <strong>Kmimos</strong> y el Usuario, por lo que no tiene responsabilidad jurídica diversa a la que la ley le otorga en su calidad de intermediario, sólo en <strong>Kmimos</strong> te ofrecemos una compensación económica sobre aquellos eventos que sufra(n) tu(s) mascota(s), , en estricto apego a nuestra Póliza no. 01-047-07000977-0000-01, así como las especificaciones que se adhieran y formen parte de dicha póliza, cuyos términos y condiciones podrás consultar íntegramente en la siguiente liga: www.<strong>kmimos</strong>.com.mx/coberturaveterinaria (la “Póliza”). Para que el Usuario tenga derecho a los beneficios de la Póliza, es indispensable tu(s) mascota(s) se encuentren bajo el cuidado de un cuidador <strong>Kmimos</strong>, por lo que el  nombre y apellido de este cuidador <strong>Kmimos</strong> debe ser el mismo que el que se encuentra en el correo de confirmación que recibió el cliente al momento de completar la reserva de estadía a través de la página web www.<strong>kmimos</strong>.com.mx; www.cani.mx ó www.<strong>kmimos</strong>.la.</p>
<p>Para garantizar la compensación por parte de <strong>Kmimos</strong>, debe darse uno de los supuestos de los detallados en el LISTADO DE EVENTOS mostrado abajo con la mascota durante la permanencia en manos del cuidador <strong>Kmimos</strong>. Todos aquellos padecimientos o enfermedad no enlistada en el LISTADO DE EVENTOS no sera amparado por la Póliza que ofrece <strong>Kmimos</strong>.</p>
<strong>LISTADO DE EVENTOS</strong>
<p>•	Lesiones generadas por caídas</p>
<p>•	Atropellamiento</p>
<p>•	Envenenamiento accidental</p>
<p>•	Ingesta de cuerpos extraños</p>
<p>•	Lesiones por ataques de otros animales</p>
<p>•	Traumatismos</p>
<p>La Póliza ampara el pago hasta por un monto de $5,000.00 M.N. (CINCO MIL PESOS 00/100 MONEDA NACIONAL) sobre aquellos eventos incluidos en el LISTADO DE EVENTOS, vía reembolso al cliente por parte de <strong>Kmimos</strong>. Para ello, <strong>Kmimos</strong> deberá recibir por parte del cliente una comprobación del pago realizado al veterinario, clínica u hospital veterinario en el que se detalle las causas que generaron dicho pago. Esta comprobación de pago será válida únicamente mediante Factura Fiscal emitida a nombre de:</p>
<p>RAZON SOCIAL: <strong>KMIMOS</strong> SAPI DE CV</p>
<p>RFC: KMI160615640</p>
<p>DIRECCIÓN FISCAL: Independencia 1018. Col. Parques del Bosque, C.P 45609. Tlaquepaque, Jal.</p>
<p>En caso de fallecimiento de la mascota mientras esté bajo el cuidado de un cuidador <strong>Kmimos</strong>, se brinda una compensación económica para gastos funerarios hasta por un monto de $10,000.00 M.N. (DIEZ MIL PESOS 00/100 MONEDA NACIONAL), vía reembolso al cliente por parte de <strong>Kmimos</strong>. Para ello, <strong>Kmimos</strong> deberá recibir por parte del cliente una comprobación del pago realizado al veterinario, clínica u hospital veterinario. Esta comprobación de pago será válida únicamente mediante Factura Fiscal (datos fiscales compartidos en los párrafos anteriores)</p>
<p>Cualquier reembolso se realiza dentro de los 30 días hábiles continuos posteriores a: 1) fecha del pago hecho por parte del cliente al veterinario, clínica u hospital veterinario y entregado, y b) Fecha de entrega del documento físico de la Factura Fiscal por parte del cliente a <strong>Kmimos</strong>.</p>
<strong>12. En caso de Abandono</strong>
<p>Si usted Usuario, como cliente, realiza una reserva de un servicio de cuidado proporcionado dentro de la plataforma <strong>Kmimos</strong> y no puede recoger a su(s) mascota(s) dentro de los siete (7) días después del final fecha de su reserva, se considerará para todos los efectos como un ‘animal abandonado o situación de abandono’, de conformidad con lo dispuesto en el Artículo 4 de la Ley de la Protección a los Animales del Distrito Federal y sus correlativos de los demás Estados de la República Mexicana (la “Ley de Protección a los Animales”), por lo que el cuidador tendrá la facultad (pero no la obligación), a su entera discreción, de poner a su(s) mascota(s) en hogares de adopción, centros relacionados con el cuidado canino, etc.</p>
<p>Asimismo, el Usuario manifiesta tener plena consciencia y conocimiento que <strong>Kmimos</strong> podrá, con fundamento en la Ley de Protección a los Animales, denunciar, ante las autoridades correspondientes, el abandono de su(s) mascota(s), estando obligadas las autoridades a exigirle al Usuario, en su calidad de propietario de su(s) mascota(s), el cumplimiento a las disposiciones contenidas en la Ley de Protección a los Animales y en su reglamento, debiendo el Usuario responder por los daños y perjuicios que su(s) mascota(s) ocasione(n) a terceros, con motivo del abandono. Las indemnizaciones correspondientes a <strong>Kmimos</strong> y/o al cuidador, según sea el caso, serán exigidas mediante el procedimiento que señalen las leyes aplicables, pero siendo el responsable sancionado administrativamente en los términos de dicho ordenamiento. </p>
<p>El Usuario reconoce que, la imposición de las sanciones previstas por Ley de Protección a los Animales y su reglamento, no lo excluye la responsabilidad civil o penal y la eventual indemnización o reparación del daño que pudiera corresponderle por el abandono de su(s) mascota(s).</p>
<p>Sin perjuicio de lo anterior, <strong>Kmimos</strong> y el cuidador buscarán, durante el periodo mencionado en el párrafo primero de este aparatado, el contacto con el Usuario para solucionar las situaciones pendientes entre los involucrados, manteniendo su compromiso con el bienestar de su(s) mascota(s).</p>
<strong>13. Mascota(s) en Riesgo de Contagio</strong>
<p>Si usted Usuario, como cliente, realiza una reserva de un servicio de <strong>Kmimos</strong> y al realizarse la inspección inicial de rutina a la llegada de su(s) mascota(s), con el cuidador <strong>Kmimos</strong> que le fue asignado, se detecta riesgo de contagio por presencia de hongos, pulgas, garrapatas, sarna, dermatitis, enfermedades preexistentes o algún agente toxico, el Usuario manifiesta conocer y por lo tanto, acepta expresamente, que la Póliza de Seguro, mencionada en el inciso 11 anterior, no será aplicable para éstos casos, siendo el Usuario el único responsable de la indemnización o reparación del daño que pudiera corresponder en caso de contagio de cualesquier mascota(s) contagiada a cargo del mismo cuidador <strong>Kmimos</strong>. Derivado de lo anterior, el Usuario en este acto, deslinda tanto a <strong>Kmimos</strong> como al cuidador <strong>Kmimos</strong>, de cualquier responsabilidad derivada o presentada con motivo de dicho contagio.</p>
<strong>14. Mascota menor a 3 meses</strong>
<p>Si usted Usuario, como cliente, realiza una reserva de un servicio de cuidado proporcionado por <strong>Kmimos</strong> y se determina que su(s) mascota(s) no cuenta(n) con la edad mínima de 3 meses, la Póliza y/o Cobertura Veterinaria no aplicará(n) en la reserva para los casos de enfermedad, debido que aún no completa su esquema de vacunación y por su(s) mascota(s) se encuentra en una etapa vulnerable.  Por lo anterior, el Usuario manifiesta expresamente estar de acuerdo y en este acto, deslinda de cualquier responsabilidad a <strong>Kmimos</strong> y al cuidador <strong>Kmimos</strong> por cualquier eventualidad que pudiera ocurrir durante la estadía de su(s) mascota(s) con el cuidador <strong>Kmimos</strong> relacionada a padecimientos y/o las complicaciones como consecuencia de su inmadurez fisiológica.</p>
<p>15. Mascota en riesgo de contagio.</p>
<p>Si usted Usuario, como cliente realiza una reserva de un servicio de cuidado proporcionado dentro de la plataforma <strong>Kmimos</strong> y no presenta al inicio de dicho servicio la cartilla de vacunación de su(s) mascota(s) que certifique que se encuentra(n) en estado de salud adecuado, usted Usuario acepta tener conocimiento y estar de acuerdo en que su(s) mascota(s) será(n) considerada(s) con estatus de esquema de vacunación no completo y la cobertura veterinaria no aplicará en la reserva para los casos de enfermedad y que <strong>Kmimos</strong> como el cuidador <strong>Kmimos</strong>, no serán responsables y por lo tanto el Usuario deslindan de todo tipo de responsabilidad derivada por cualquier eventualidad que pudiera ocurrir durante su estadía con el cuidador <strong>Kmimos</strong>, relacionada a padecimientos y/o las complicaciones derivadas de éstos. El cuidador <strong>Kmimos</strong>, tendrá la facultad opcional de acudir al Médico veterinario zootécnico en caos que su(s) mascota(s) se encuentra(n) con síntomas de enfermedad, siendo responsabilidad y obligación plena del Usuario, reembolsar los gastos generados por estas revisiones médicas.</p>
<strong>15. Domicilio. </strong>
<p>12.1. Cualquier notificación o comunicación dirigida a <strong>Kmimos</strong> deberá enviarse a Independencia 1018. Col. Parques del Bosque, C.P 45609. Tlaquepaque, Jal. Teléfono 55 4742 3162. Correo Electrónico: contactomex@<strong>kmimos</strong>.la</p>
<strong><u>II. Políticas de Privacidad.</u></strong>
<p><strong>Kmimos</strong> (en adelante denominado "<strong>Kmimos</strong>" o "<strong>kmimos</strong>.mx" o "<strong>kmimos</strong>.com.mx" o "<strong>kmimos</strong>.la") respeta su privacidad. Debido a que reunimos información importante de nuestros usuarios, visitantes, suscriptores y clientes (colectivamente "usted" o "su"), hemos establecido esta Política de privacidad como un medio para comunicar nuestra información de recopilación y difusión prácticas. Al acceder o utilizar <strong>kmimos</strong>.la (el "Sitio") o cualquiera de nuestras aplicaciones móviles o servicios (el Sitio, y este tipo de aplicaciones y servicios, colectivamente, "Servicios"), usted reconoce y acepta que esta Política de Privacidad y también de acuerdo a los Términos de Servicio</p>
<p>Nuestros objetivos principales en la recopilación de información son para proporcionar y mejorar nuestros servicios, y para que los usuarios puedan disfrutar de los Servicios. Así mismo utilizar su información personal u otra información para comunicarnos con usted en el futuro para informarle sobre productos, promociones o servicios que creemos serán de interés para usted.</p>
<p>En la recolección y tratamiento de los datos personales que usted nos proporciona, cumplimos todos los principios que marca la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (la “Ley”) y su Reglamento: licitud, calidad, consentimiento, información, finalidad, lealtad, proporcionalidad y responsabilidad.</p>
<p>Si usted no está de acuerdo en que utilicemos la información que nos ha compartido para brindarle un mejor servicio, publicidad o promociones de <strong>Kmimos</strong> por favor envié un correo notificando al respecto a contactomex@<strong>kmimos</strong>.la, en un plazo de 5 días hábiles después de haber otorgado su consentimiento a la presente Política de Privacidad. En estos casos, sus datos personales, serán colocados en una Lista de Exclusión, en la cual únicamente personas autorizadas por <strong>Kmimos</strong> tendrán acceso a sus datos personales.</p>
<p>En caso de requerir mayor información, podrá solicitarla mediante una solicitud por escrito enviada al domicilio de <strong>Kmimos</strong> ubicado en: Independencia 1018. Col. Parques del Bosque, C.P 45609. Tlaquepaque, Jal., o bien, a la dirección de correo electrónico señalado en el párrafo anterior.</p>
<p>Visitante del Sitio / datos de usuario</p>
<p>a) Recopilamos información personal (como su nombre, dirección física, número de teléfono y dirección de correo electrónico) y otra información que proporcione en relación con la prestación o la mejora de los Servicios (incluyendo para procesar su inscripción o responder a una solicitud). Además, si usted proporciona información personal por una cierta razón, podemos usar la información personal en relación con la razón por la cual fue proporcionada. Cuando usted utilice los Servicios, Toda la información de identificación personal que se denominan colectivamente en lo sucesivo como "Información Personal". Si usted llena un formulario de contacto o recomendación o nos envía un correo electrónico, usaremos esa información para responder a su solicitud.</p>
<p><strong>Kmimos</strong> podrá transferir los datos personales que obren en sus bases de datos a cualesquiera de sus empresas y/o a sus empresas filiales y/o subsidiarias e incluso a terceras personas, nacionales o extranjeras, y/o aquellos terceros que, por la naturaleza de sus trabajos o funciones, tengan la necesidad de tratar y/o utilizar los mismos, con el propósito de cumplir aquellas obligaciones que se derivan de la relación jurídica existente entre dichos usuarios como titulares de los datos personales y las empresas antes señaladas, salvo que los titulares respectivos manifiesten expresamente su oposición, en términos de lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, salvo que los titulares respectivos manifiesten expresamente su oposición, en términos de lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.</p>
<p>Todo tercero a quien se realice la transferencia señalada, en su caso, manifiesta previamente conocer las presentes Políticas de Privacidad y obligarse en sus términos.</p>
<p><strong>Kmimos</strong> podrá compartir datos personales con las autoridades federales y locales, en cumplimiento a las obligaciones contempladas en la legislación aplicable y/o en cumplimiento a requerimientos por parte de éstas o cuando sea en circunstancias urgentes para proteger la seguridad personal de los usuarios de los Servicios o el público, o para proteger contra la responsabilidad legal.</p>
<p>Podremos utilizar su información personal u otra información para comunicarnos con usted en el futuro para informarle sobre productos o servicios que creemos serán de interés para usted.</p>
<p>Usted voluntariamente nos proporcione información personal, usted está consintiendo a nuestro uso de la misma de acuerdo con esta Política de Privacidad. Si usted proporciona información personal a nosotros, usted reconoce y acepta que dicha información personal puede ser transferida desde su ubicación actual a las oficinas y servidores de <strong>Kmimos</strong> y los terceros autorizados a que se refiere el presente documento se encuentra en los Estados Unidos Mexicanos.</p>
<p>Utilizamos la información que recopilamos para proporcionar y mantener los servicios que consideremos apropiadas en nuestra discreción. Al visitar o utilizar los servicios, podemos almacenar algunos o todos de los siguientes: la dirección IP desde la que se accede a los servicios, la fecha y la hora, la dirección IP del sitio web desde el que se conectó a los Servicios, el nombre del archivo o palabras que ha buscado en nuestro Sitio, artículos hace clic en una página y el navegador y sistema operativo utilizado. Esta información se utiliza para medir el número de visitantes a las diferentes secciones de nuestro sitio e identificar el rendimiento del sistema.</p>
<p>Utilizamos los servicios de métricas web para rastrear la actividad en los Servicios. Utilizamos esta información para ayudarnos a desarrollar los Servicios, analizamos los patrones de uso, y para que los servicios más útiles. Esta información no se utiliza para asociar los términos de búsqueda o patrones de navegación del sitio con los usuarios individuales.</p>
<p>Seguridad</p>
<p>Tenga en cuenta que los datos que se transporta a través de una red abierta, como Internet o el correo electrónico, puede ser accesible a cualquier persona. No podemos garantizar la confidencialidad de cualquier comunicación o material transmitido a través de este tipo de redes abiertas. Al revelar cualquier información personal a través de una red abierta, debe seguir siendo conscientes del hecho de que es potencialmente accesible a los demás, y por lo tanto, puede ser recogida y utilizada por otras personas sin su consentimiento. Sus datos pueden perderse durante la transmisión o pueden ser accedidos por terceros no autorizados. No aceptamos responsabilidad alguna por pérdidas directas o indirectas en cuanto a la seguridad de su información personal o datos durante su transferencia a través de Internet. Por favor, utilice otro medio de comunicación si usted piensa que esto es necesario o prudente por razones de seguridad.</p>
<p>Por razones de seguridad de red y para asegurar que nuestros servicios se mantienen a disposición de todos los usuarios, que emplean programas de software comercial para controlar el tráfico de red y tratar de identificar intentos no autorizados de cargar o cambiar información o causar daños. </p>
<p>Enlaces externos Sitio</p>
<p><strong>Kmimos</strong> puede enlazar a sitios web o servicios de terceros que pueden incluir u ofrecer productos o servicios de terceros. Es su responsabilidad mantener la información privada y confidencial. Estos sitios de terceros tienen políticas de privacidad separadas e independientes. <strong>Kmimos</strong> no controla ni garantiza la exactitud, relevancia, puntualidad o integridad de la información contenida en un sitio web de terceros o servicio y no tiene responsabilidad alguna por los contenidos y actividades de estos sitios web o servicios. Si hace clic en un enlace a un sitio web de terceros o servicio, se le deja los servicios y está sujeto a las políticas de privacidad y seguridad de los propietarios / patrocinadores del sitio web de terceros o servicio y no a esta Política de Privacidad. <strong>Kmimos</strong> no puede autorizar el uso de materiales con derechos de autor contenidos en los sitios web o servicios vinculados. Los usuarios deben solicitar la autorización del patrocinador del sitio web o servicio vinculado. <strong>Kmimos</strong> no es responsable de las transmisiones de los usuarios reciben de sitios web o servicios vinculados.</p>
<p>Prohibiciones</p>
<p><strong>Kmimos</strong> no voluntariamente o intencionalmente enlazará al usuario a cualquier sitio web que exhibe el odio, prejuicio o discriminación. <strong>Kmimos</strong> se reserva el derecho a denegar o retirar cualquier enlace por cualquier razón. Nosotros buscamos proteger la integridad de nuestros servicios en todo momento y agradecemos cualquier comentario.</p>
<p>Limitaciones al uso o divulgación de sus Datos Personales</p>
<p>El Usurario puede dirigirse a <strong>Kmimos</strong> para el caso de que desee limitar el uso o divulgación de sus datos personales, para dejar de recibir información o publicidad de los servicios que proporciona <strong>Kmimos</strong>, enviando su solicitud al área de “Privacidad de Datos”, a través de la cuenta de correo electrónico: contactomex@<strong>kmimos</strong>.la dirigido a Rob Cuevas.</p>
<p>Derechos ARCO y consentimiento otorgado</p>
<p>Como titular de datos personales, usted podrá ejercer los Derechos ARCO (Acceso, Rectificación, Cancelación y Oposición al tratamiento de sus datos personales), o bien, revocar el consentimiento que usted haya otorgado a <strong>Kmimos</strong>, para el tratamiento de sus datos personales, enviando su solicitud, directamente al área de "Privacidad de Datos" a través de la cuenta de correo electrónico: contactomex@<strong>kmimos</strong>.la o bien, solicitándolo por escrito, al domicilio ubicado en: Independencia 1018. Col. Parques del Bosque, C.P 45609. Tlaquepaque, Jal. Dicha solicitud deberá contener por lo menos: (a) nombre, firma autógrafa del titular y domicilio u otro medio para comunicarle la respuesta a su solicitud; (b) los documentos que acrediten su identidad o, en su caso, la representación legal; (c) la descripción clara y precisa de los datos personales respecto de los que se solicita ejercer alguno de los Derechos ARCO, (d) la manifestación expresa para revocar su consentimiento al tratamiento de sus datos personales y por tanto, para que no se usen; y (e) cualquier otro elemento que facilite la localización de los datos personales.</p>
<p>Una vez presentada su solicitud en el formato preestablecido, el área de “Privacidad de Datos” comunicará en un plazo máximo de 20 días hábiles, contados desde la fecha en que se recibió dicha solicitud, la respuesta de la misma. En caso de requerir mayor información y/o documentación necesaria el área de “Privacidad de Datos” se pondrá en contacto con usted en un plazo de 5 días hábiles contados desde la fecha de recepción de su solicitud, por lo que usted contará con 10 días hábiles posteriores a dicha comunicación, para atender este requerimiento. De lo contrario su solicitud se tendrá por no presentada.</p>
<p>Los términos y plazos indicados en los párrafos anteriores, podrán ser ampliados una sola vez en caso de ser necesario y se le deberá notificar a través de los medios de contacto que haya establecido, señalando las razones de dicha ampliación, de conformidad con el artículo 32 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.</p>
<p>La revocación y el ejercicio de los Derechos ARCO serán gratuitos, así como la reproducción en copia simple o envío por correo electrónico.</p>
<p>Cambios a nuestra Política de Privacidad</p>
<p>Cualquier política de privacidad revisada se aplicará tanto a la información que ya tenemos sobre usted en el momento del cambio, y cualquier información generada o recibida después de que el cambio entre en vigencia. Le recomendamos encarecidamente que vuelva a leer periódicamente esta Política de Privacidad, para ver si ha habido algún cambio en nuestras políticas que pueden afectarle. El uso continuado de los Servicios después de cualquier cambio o revisión de esta Política de Privacidad deberá indicar su acuerdo con los términos de dicha Política de privacidad actualizada.</p>
<p>En caso de que exista alguna actualización o modificación, <strong>Kmimos</strong> lo hará de su conocimiento a través de nuestro Portal (http://www.<strong>kmimos</strong>.com.mx/).</p>
<p>Por lo consiguiente acepto la Política de Privacidad dispuesta en este documento.</p>
<strong><u>III. Guía del Servicio.</u></strong>
<strong>1. Certificación.</strong>
<p>1.1. Certificación </p>
<p>a. Se hace una prueba de conocimiento vía telefónica o electrónicamente haciendo un cuestionario desarrollado por el equipo de <strong>Kmimos</strong>.</p>
<p>b. Para que se considere que el resultado de la encuesta es positiva, se debe aprobar el 80% de las preguntas hechas en el mismo.  En caso de aprobar se procede al paso para registrar los campos en la página web.  En caso de no aprobar debe esperar hasta 10 días hábiles para nuevamente tomar la encuesta y se le notifica al aspirante a cuidador asociado que no se ha cumplido con el mínimo conocimiento para cuidados de perros definidos en el proceso de certificación. Si el aspirante ya se registró en la página web, se le colocará en estatus inactivo, hasta que <strong>Kmimos</strong> lo contacte y lleve a cabo el proceso de certificación y el potencial cuidador lo apruebe.</p>
<p>c. Después de ser aprobada la certificación se notifica al candidato para solicitarle comprobante de domicilio, identificación oficial y cuenta interbancaria.</p>
<p>d. Se registran los datos del cuidador en un control interno para tener toda la información integrada.</p>
<p>e. Una vez registrada la información se continúa con el siguiente paso.</p>
<p>1.2.	 Examen Psicométrico.</p>
<p>a. El candidato recibe vía correo electrónico un examen psicométrico, el cual debe ser aprobado por parte del cuidador.</p>
<p>b. Después de terminar esta encuesta el candidato espera la notificación de su aprobación.  En caso de ser positiva continua el proceso de certificación.  En caso de ser negativa, el cuidador podrá nuevamente tomar la prueba luego de transcurridos 30 días continuos desde el día que la tomó la primera vez, y no podrá darse de alta como cuidador <strong>Kmimos</strong>.</p>
<p>1.3. Activación de perfil.</p>
<p>a. Una vez que se aprueba el perfil, se activa el perfil por parte del equipo de <strong>Kmimos</strong>  se le notifica al cuidador.</p>
<strong>2. Plataforma.</strong>
<p>Acceso a página web.</p>
<p>El usuario accede a la plataforma a través de cualquiera de los dominios www.<strong>kmimos</strong>.la, www.cani.mx, <strong>kmimos</strong>.com.mx, <strong>kmimos</strong>.mx </p>
<p>En la página de inicio puede tomar cinco decisiones:</p>
<p>2.1. Dar click en el botón de registrarse como cuidador que llevara el siguiente proceso:</p>
<p>a. Registrar sus datos personales, información de su domicilio, servicios a ofrecer, precios y aceptar los términos y condiciones de uso de la plataforma.</p>
<p>b. Seguir el proceso de certificación de <strong>Kmimos</strong>.</p>
<p>c. Buscar cuidadores ingresando fechas de algún viaje y su ubicación para que le desplieguen los cuidadores disponibles en área y fechas, que a más detalle seguirán estos pasos:</p>
<p>i. Se desplegará una lista de cuidadores que dan el servicio.</p>
<p>ii. Seleccionará el cuidador que guste ver su perfil.</p>
<p>iii. Aparecerá la información del perfil y opciones para contactar o contratar un servicio por parte del cuidador.</p>
<p>2.2. Si escoge la opción de "cita" llenará un formulario para dejar sus datos y agendar una cita, convirtiéndose en un cliente.</p>
<p>2.3. Posteriormente le aparecerá una pantalla notificando que se realizó su registro exitosamente de la cita y le llegara un correo a la dirección de email registrada por el cuidador, así como también llegará un correo electrónico de notificación a los administradores de <strong>Kmimos</strong>.</p>
<p>2.4. Si escoge la opción de "reserva" llenará un formulario para dejar sus datos, agendar su reservación y escoger la manera de pago, convirtiéndose en un cliente.</p>
<p>Posteriormente le aparecerá un pantalla notificando de que se realizó su registro exitosamente de la reserva y le llegará un email a la dirección de correo electrónico registrada por el cuidador, así como también llegará un correo de notificación a los administradores de <strong>Kmimos</strong>.</p>
<p>2.5. Si escoge la opción de "servicio adicional" llenará un formulario para dejar sus datos, contratar el servicio y escoger la manera de pago, convirtiéndose en un cliente.</p>
<p>Posteriormente le aparecerá un pantalla notificando que se realizó exitosamente el registro del servicio y le llegará un email a la dirección de correo electrónico registrada por el cuidador, así como también llegará un correo de notificación a los administradores de <strong>Kmimos</strong>.</p>
<p>2.6. Dar click en el botón de registrarse como cliente que llevara el siguiente proceso:</p>
<p>a. Registrar sus datos personales, datos de su mascota, forma de pago y aceptar los términos y condiciones de uso de la plataforma.</p>
<p>b. Se saldrá del sitio</p>
<p>c. Nos escribirá por medio del chat de la página.</p>
<strong>3. Logística de plataforma y servicios.</strong>
<p>3.1. Una vez que  el cliente registró una cita suceden los siguientes pasos:</p>
<p>a. La plataforma web genera un correo dirigido al cliente con la información registrada y mencionando que nos contactaremos con el cliente en menos de 24 horas,  así como también llegará un correo de notificación a los administradores de <strong>Kmimos</strong>.</p>
<p>b. La plataforma y/o el personal de <strong>Kmimos</strong> emite un mensaje hacia el cuidador para saber si acepta la cita para conocer al cliente con la información que registro, solamente contemplando el nombre del cliente y la información de la mascota o mascotas a cuidar, y existen dos posibles opciones. (En el caso de que sea la plataforma, se enviará sobre el correo con la información registrada y dos botones preguntando si acepta la cita, si es el caso del personal <strong>Kmimos</strong>, se contactarán por algún medio de comunicación con el cuidador para saber su decisión):</p>
<p>i. Que acepte la cita del cliente: Una vez que acepta se envía toda la información registrada anexando todos los datos de contacto del cliente para que el cuidador pueda confirmar la cita y acudir a ella </p>
<p>ii. Que no acepte la cita y el personal de <strong>Kmimos</strong> deba recomendar otro cuidador al cliente: El personal de <strong>Kmimos</strong> buscará a recomendar a un cuidador que sea del agrado del cliente  para que escoja alguna opción y se puede realizar la cita.</p>
<p>Una vez que  el cliente registró una reserva suceden los siguientes pasos:</p>
<p>i. La plataforma web genera un correo dirigido al cliente con la información registrada y mencionando que nos contactaremos con el cliente en menos de 24 horas, así como también llegará un correo de notificación a los administradores de <strong>Kmimos</strong>.</p>
<p>ii. La plataforma y/o el personal de <strong>Kmimos</strong> emite un mensaje hacia el cuidador para saber si acepta la reserva del cliente con la información que registro, solamente contemplando el nombre del cliente y la información de la mascota o mascotas a cuidar, y existen dos posibles opciones. </p>
<p>Que acepte la reserva del cliente: </p>
<p>a. Una vez que acepta, se envía toda la información anexando todos los datos de contacto del cliente para que el cuidador pueda confirmar la reserva y realizar el servicio..</p>
<p>b. Se enviará la confirmación de la reserva y el cargo con copia al cuidador y cliente.</p>
<p>4. Se iniciara el proceso de la estadía.</p>
<p>Que no acepte el servicio  y el personal de <strong>Kmimos</strong> deba recomendar otro cuidador al cliente</p>
<p>b. El personal de <strong>Kmimos</strong> buscara a recomendar a un cuidador que sea del agrado del cliente  para que escoja alguna opción y se puede realizar la reservación</p>
<p>4. Una vez que  el cliente registró un servicio adicional suceden los siguientes pasos:</p>
<p>a. La plataforma web genera un correo dirigido al cliente con la información registrada y mencionando que nos contactaremos con el cliente en menos de 24 horas.</p>
<p>b. La plataforma y/o el personal de <strong>Kmimos</strong> emite un mensaje hacia el cuidador para saber si acepta el servicio adicional que quiere el cliente con la información que registro, solamente contemplando el nombre del cliente y la información del servicio a realizar para la mascota, y existen dos posibles opciones. (En el caso de que sea la plataforma, se enviara sobre el correo con la información registrada y dos botones preguntando si acepta el servicio, si es el caso del personal <strong>Kmimos</strong>, se contactaran por algún medio de comunicación con el cuidador para saber su decisión).</p>
<p>Que acepte el servicio para la mascota del cliente. </p>
<p>a. Una vez que acepta, se envía toda la información anexando todos los datos de contacto del cliente para que el cuidador pueda confirmar el servicio.</p>
<p>b. Se enviará la confirmación del servicio adicional y el cargo con copia al cuidador y cliente.</p>
<p>d. Posteriormente se iniciará el proceso del servicio adicional.</p>
<p>Que no acepte el servicio y el personal de <strong>Kmimos</strong> deba recomendar otro cuidador al cliente.</p>
<p>a. El personal de <strong>Kmimos</strong> buscará recomendar a un cuidador que sea del agrado del cliente  para que escoja alguna opción y se puede realizar el servicio adicional</p>
<strong>4. Estadía.</strong>
<p>El cuidador procede a cuidar a la mascota con la que fue reservado su servicio a través de <strong>Kmimos</strong>, con lo que llevará a cabo la recolección y entrega (puede incluir o no la búsqueda a domicilio), toma de fotografías y cuidado de la mascota de manera diaria durante el tiempo que fue reservado el servicio.  La recolección y entrega puede ocurrir a domicilio o en casa del cuidador dependiendo del tipo de servicio que declara el cuidador en su perfil <strong>Kmimos</strong>.</p>
<strong>5. Recolección y entrega de mascotas.</strong>
<p>5.1. El cuidador sabrá por medio del comprobante de la reserva si esperará la llegada de la mascota a cuidar a su domicilio o en su caso deberá ir a recoger la mascota al domicilio del cliente. Aplicará el mismo caso para ir a dejar a la mascota una vez finalizada la estadía, suponiendo que el cliente lo recoja o el cuidador la vaya a entregar.</p>
<p>5.2. Se recomienda que adicional a la entrega de la mascota del cliente al cuidador, también se entregue el alimento por los días necesarios, plato de la mascota, correa, cama, juguetes y/o accesorios.</p>
<p>Nota: <strong>Kmimos</strong> queda exento de cualquier daño, pérdida o mal uso de estos objetos que el cliente entregue al cuidador, así como también el hecho del cobro por el alimento que sea necesario extra para la estadía de la mascota. Igualmente a cualquier daño a la propiedad del cuidador que la mascota del cliente haga.</p>
<strong>6. Fotografías y videos. </strong>
<p>6.1. El cuidador tomará fotografías o videos desde el primer instante que recibe a la mascota, y las enviará según sea el caso que haya recibido a la mascota, fotografías en un horario de la mañana (8am a 10am), y de noche (8pm a 10pm). Esto será de manera diaria mientras la mascota este bajo su cargo.</p>
<p>6.2. Las fotografías o videos se compartirán al cliente por medio de la plataforma o vía WhatsApp dependiendo sea el caso en el momento. Si se envía el material vía WhatsApp se enviará una copia de esto a <strong>Kmimos</strong> para su revisión.</p>
<strong>7. Servicios adicionales.</strong>
<p>Los cuidadores podrán ofrecer servicios adicionales a la estadía con la finalidad de que sean contratados adicionalmente o independientemente a una estadía.</p>
<p>Estos servicios son:</p>
<p>•	Baño </p>
<p>•	Corte de pelo y uñas</p>
<p>•	Paseos</p>
<p>•	Guardería</p>
<p>•	Visita al veterinario</p>
<p>•	Consulta veterinaria</p>
<p>•	Acupuntura</p>
<p>•	Terapia de sanación</p>
<p>•	Adiestramiento canino</p>
<p>•	Limpieza dental</p>
<p>Su ejecución dependerá de cada cuidador según sea el servicio y situación que se presente. </p>
<strong>8. Cancelación o cambio a las citas, reservaciones o servicios adicionales.</strong>
<p>Existen cuatro tipos de opciones para los cambios o cancelaciones:</p>
<p>8.1. Cancelación de una cita:</p>
<p>a. Si el cliente cancela la cita, se enviara una notificación al cuidador y <strong>Kmimos</strong></p>
<p>b. Si el cuidador cancela la cita, se enviara una notificación al cliente y <strong>Kmimos</strong></p>
<p>8.2. Cancelación de reservación:</p>
<p>a. Si el cliente cancela la reservación, con menos de 48 horas a la fecha y hora de entrada o check-in, se enviara una notificación al cuidador y <strong>Kmimos</strong>, y se hará el cargo equivalente al 20% de la reservación </p>
<p>b. Si el cuidador cancela la reservación con menos de 48 horas a la fecha y hora de entrada o check-in, se enviara una notificación al cliente y <strong>Kmimos</strong>, y se hará el cargo equivalente al 20% de la reservación </p>
<p>8.3. Cancelación de servicio adicional:</p>
<p>a. Si el cliente cancela la reservación, se enviara una notificación al cuidador y <strong>Kmimos</strong>, y se hará el cargo de un 20% por el costo del servicio.</p>
<p>b. Si el cuidador cancela la reservación, se enviara una notificación al cliente y <strong>Kmimos</strong>, y se hará el cargo de un 20% por el costo del servicio.</p>
<p>8.4. Cambio de información de una cita:</p>
<p>a. Si el cliente cambio la información la cita, se enviara una notificación al cuidador y <strong>Kmimos</strong>, para esperar la aprobación del cuidador y proceder con la cita</p>
<p>b. Si el cuidador cambio la información la cita, se enviara una notificación al cliente y <strong>Kmimos</strong>, para esperar la aprobación del cliente y proceder con la cita</p>
<p>8.5. Cambio de información de una reservación:</p>
<p>a. Si el cliente cambio la información la reservación, se enviara una notificación al cuidador y <strong>Kmimos</strong>, para esperar la aprobación del cuidador y proceder con los cambios, cargos o devoluciones de la reservación.</p>
<p>b. Si el cuidador cambio la información la cita, se enviara una notificación al cliente <strong>Kmimos</strong>, para esperar la aprobación del cliente y proceder con los cambios, cargos o devoluciones de la reservación.</p>
<p>8.6. Cambio de información de un servicio adicional</p>
<p>a. Si el cliente cambio la información de un servicio adicional, se enviara una notificación al cuidador y <strong>Kmimos</strong>, para esperar la aprobación del cuidador y proceder con los cambios, cargos o devoluciones de la reservación.</p>
<p>b. Si el cuidador cambio la información de un servicio adicional, se enviara una notificación al cliente y <strong>Kmimos</strong>, para esperar la aprobación del cliente y proceder con los cambios, cargos o devoluciones de la reservación.</p>
<strong>9. Cargos adicionales y comisiones.</strong>
<p><strong>Kmimos</strong> podrá generar cargos adicionales y/o comisiones según las condiciones de los servicios contratados a través de la plataforma que se enlistan en el siguiente apartado.</p>
<p>9.1. Reservación express: Se cobra un monto del 50% de una noche de la estadía escogida si la reservación contratada se agenda con menos de 24 hrs. a la ejecución del servicio.</p>
<p>9.2. Servicio adicional express: Se cobra un monto del 50% del servicio adicional contratado si se agenda con menos de 24 hrs. a la ejecución del servicio.</p>
<p>9.3. Comisión por uso de plataforma al cliente: </p>
<p>a. <strong>Kmimos</strong> hará un cargo de 20% sobre el monto a pagar por cada noche reservada, contratadas por la plataforma, por concepto  de gastos administrativos.</p>
<p>b. <strong>Kmimos</strong> hará un cargo de 20% sobre el monto de cada servicio adicional contratado por la plataforma, por concepto  de gastos administrativos.</p>
<strong>10. Encuesta de satisfacción y evaluación del servicio.</strong>
<p><strong>Kmimos</strong> para garantizar un servicio de calidad podrá contactar a los clientes que hayan tenido alguna cita, reservación o servicio adicional contratado por la plataforma. Se contactara por vía telefónica, correo electrónico, o medios web (whatsapp, plataforma, etc.) En esta encuesta se llevara a cabo un cuestionario realizado por el personal de <strong>Kmimos</strong> enfocado a mejorar el servicio de la plataforma web y experiencia vivida por el servicio obtenido.</p>
<p>De igual manera, <strong>Kmimos</strong> permitirá la evaluación de los cuidadores y clientes, por medio de un modelo de ponderación, evaluado los siguientes puntos para cualquiera de los dos casos:</p>
<p>10.1. Cuidador:</p>
<p>a. Limpieza</p>
<p>b. Confianza</p>
<p>c. Puntualidad</p>
<p>d, Cuidado</p>
<p>10.2. Cliente:</p>
<p>a. Puntualidad en pago;</p>
<p>b. Certeza de información proporcionada. </p>
<strong>11. Donaciones.</strong>
<p><strong>Kmimos</strong> podrá ser un conducto por el cual algunas Fundaciones puedan obtener donaciones económicas o a través de insumos por parte de los clientes, que pueden ser traducidas en transferencias electrónicas o entrega de los insumos, dependiendo la elección de la fundación.</p>
<strong>12. Newsletter.</strong>
<p><strong>Kmimos</strong> podrá emitir información como considere, vía correo electrónico, telefónica o medios web a los usuarios que estén inscrito o registrados en la plataforma, con la opción de que estos usuarios puedan cancelar la subscripción a este newsletter.</p>
<strong><u>IV. Productos Prohibidos.</u></strong>
<p>Restricciones y prohibiciones:</p>
<p>Al usar el sitio, usted presta su consentimiento a las restricciones y prohibiciones para la publicación de productos que aquí se detallan.</p>
<p>Esta lista no debe considerarse exhaustiva y se actualizará de forma continua. Si no está seguro respecto de la legalidad o conveniencia de la publicación del producto que Ud. desea ofertar en el sitio, por favor contáctese con nosotros.</p>
<p>Prohibiciones Generales:</p>
<p>Se prohíbe publicar cualquier producto, servicio o equipo que este restringido o prohibido por un gobierno federal, estatal o local, en cualquier país o jurisdicción. Tome en cuenta que algunos productos pueden estar prohibidos por leyes de una jurisdicción distinta a la cual usted reside. Al colocar un anuncio en <strong>Kmimos</strong>, usted confirma que su anuncio cumple con todas las reglamentaciones aplicables en los países a los cuales está dirigido el anuncio.</p>
<p>A continuación se detalla una lista de algunas categorías de artículos cuya publicación en el Sitio está prohibida o restringida. Esta enumeración es enunciativa y no incluye todas las posibilidades existentes, por lo que usted como vendedor es responsable de garantizar que no publicará un producto que se encuentre prohibido por la ley o que sea similar en uso u objetivo a los listados a continuación. <strong>Kmimos</strong> se reserva el derecho de imponer nuevas restricciones y prohibiciones a su sola discreción.</p>
<p>Se prohíbe explícitamente la publicación de los siguientes artículos:</p>
<p>1.	Material pornográfico, servicios de acompañantes, prostitución o contenido relacionado con estos servicios. Pornografía infantil, pornografía que describa modelos menores de edad y prácticas sexuales ilegales. </p>
<p>2.	Anuncios que promuevan la violencia o pronunciarse en contra de un grupo definido por raza u origen étnico, color, nacionalidad, religión, discapacidad, sexo, edad, orientación sexual o identidad sexual. Los usuarios del sitio deben utilizar textos que guarden la sensibilidad adecuada para aquellos que puedan leerlos. También se prohíben materiales nazis, de la KKK, de organizaciones que inciten al odio y de organizaciones terroristas.</p>
<p>3.	Anuncios que promocionen técnicas de marketing masivo como listas de correos, software de correos electrónicos masivos, mensajes masivos.</p>
<p>4.	Promoción de la copia o distribución de contenido protegido con derechos de autor sin consentimiento de su propietario y que de otra manera no esté permitido por la ley. Falsificaciones, réplicas no autorizadas o artículos no autorizados como prendas de vestir, relojes, bolsos, anteojos de sol u otros accesorios de marca.</p>
<p>5.	Promoción de imitaciones o productos falsificados. Artículos que contengan la imagen, nombre o firma de otra persona, a menos que los productos fueran realizados o autorizados por la persona cuya semejanza, imagen, nombre o firma se ha utilizado. Copias no autorizadas (piratas, duplicados, copias de seguridad, etc.) de programas de software, videojuegos, discos musicales, películas, programas de televisión, fotografías u otras obras protegidas.</p>
<p>6.	Productos que sean o se asemejen a identificaciones oficiales del gobierno, como certificados de nacimiento, licencias de conducir, visas o pasaportes, tarjetas de seguro social, documentos de inmigración, diplomas y títulos profesionales.</p>
<p>7.	Identificaciones o artículos de uniforme que aparenten ser o sean similares a uniformes militares oficiales. Insignias de las fuerzas de seguridad o insignias oficiales de cualquier autoridad pública</p>
<p>8.	Drogas, artículos relacionados y ayudas para superar controles de drogas. Esto incluye drogas ilegales, drogas herbales y drogas respecto de las cuales es necesaria prescripción médica para su compra. También incluye las materias primas, precursores u objetos destinados a la producción o consumo de drogas.</p>
<p>9.	Promoción de productos que se obtienen a partir de especies en vías de extinción o amenazadas. Esto incluye, pero no se limita a, la venta de productos derivados de elefantes, tiburones, tigres, ballenas, rinocerontes y delfines o animales vivos o partes de animales que se encuentren protegidos por la Convención sobre el Comercio Internacional de Especies Amenazadas de Fauna y Flora Silvestres (\'CITES\').</p>
<p>10.	Promoción de fuegos artificiales y dispositivos pirotécnicos. </p>
<p>11.	Promoción de la piratería y de las herramientas que ayudan a infringir los derechos de autor.</p>
<p>12.	Hormona de crecimiento humana (HGH) inyectable.</p>
<p>13.	DHEA y melatonina.</p>
<p>14.	Esteroides anabolizantes, anabólicos para aumentar los músculos, suplementos de esteroides para el culturismo y contenido relacionado.</p>
<p>15.	Efedra y efedrina (incluidos los productos que contienen efedra o efedrina). </p>
<p>16.	Curas milagrosas para enfermedades de personas o animales. Afirmaciones de cualidades terapéuticas falsas o no probadas científicamente.</p>
<p>17.	Promoción de contenido para celulares que no muestre la estructura de precios de manera clara y precisa.</p>
<p>18.	Servicios de redacción de ensayos o de realización de exámenes.</p>
<p>19.	Nombres propios para promocionar sitios de búsqueda de personas, sitios de investigación de médicos y abogados, y sitios de detectives.</p>
<p>20.	Solicitudes de donaciones que no estén exentas de impuestos.</p>
<p>21.	Tabaco y de productos relacionados con el tabaco.</p>
<p>22.	Productos que se diseñaron principalmente para evadir las leyes de tránsito.</p>
<p>23.	Armas de cualquier tipo, como por ejemplo armas de fuego, componentes de armas de fuego, municiones, navajas plegables, navajas automáticas y navajas de mariposa así como municiones, artillería militar, armas de asalto, y sus repuestos o accesorios. Incluye también las réplicas, o artículos de aspecto similar o las imitaciones de armas de fuego. </p>
<p>24.	Artículos arqueológicos, reliquias culturales y artículos que estén protegidos bajo las leyes internacionales.</p>
<p>25.	Billetes, monedas, sellos, bonos, giros postales, y cualquier otro valor, así cualquier equipo o elemento para la producción de dichos artículos.</p>
<p>26.	Boletos para espectáculos y eventos (a menos de que usted pueda asegurar que su transacción no viole cualquier ley aplicable o las condiciones indicadas en el propio boleto).</p>
<p>27.	Personas, cuerpos humanos, órganos humanos o cualquier parte del cuerpo humano.</p>
<p>28.	Artículos robados.</p>
<p>Antes de publicar un producto en el Sitio, usted deberá estar seguro que conoce las limitaciones legales que podría tener para realizar la publicación y de debe garantizar que la transacción que busca realizar es legal y que no viola ninguna obligación contractual.</p>
<p>Los siguientes productos, aunque no están prohibidos, su publicación se rige por leyes específicas que pueden variar de país en país o que requieren permisos especiales específicos por cada país. Por favor consulte con <strong>Kmimos</strong> antes de publicar algún producto que entre dentro de estas categorías para asegurarse que cumple con la normatividad específica.</p>
<p>29.	Promoción de bebidas de alta graduación alcohólica y bebidas espirituosas.</p>
<p>30.	Promoción de sitios web de juegos de apuestas en línea.</p>
<p>31.	Farmacias en línea y de medicamentos con receta.</p>
</div>';

$NEW_HTML_TERMINOS = "";
$parrafos = explode("\n", $HTML_TERMINOS);
foreach ($parrafos as $parrafo) {
	$NEW_HTML_TERMINOS .= "<p>".$parrafo."</p>";
}

echo $NEW_HTML_TERMINOS; ?>